from enum import Enum


class WorkRequestStatus(str, Enum):
    """Work request status values"""
    REQUESTED = "Requested"
    COMPLETED = "Completed"


class AssetType(str, Enum):
    """Asset types from Bruce BEM system"""
    UNSPECIFIED = None
    AIR_COOLING = "Air Cooling"
    AIR_HEATING = "Air Heating"
    AMENITY = "Amenity"
    ART_SCULPTURE = "Art (Paint/sculpture)"
    BADGE_IDENTIFICATION = "Badge / Identification"
    BUILDING = "Building"
    CAMPUS = "Campus"
    CARPET = "Carpet"
    CEILING_SURFACE = "Ceiling (surface)"
    COMPLEX = "Complex"
    COMPUTER = "Computer"
    COPIER_MFD_FLEET = "Copier / MFD fleet"
    DECORATIVE_ELEMENT = "Decorative element"
    DESK = "Desk"
    EMERGENCY_SIGNAGE = "Emergency Signage"
    EQUIPMENT = "Equipment"
    FIRE_EXTINGUISHING = "Fire Extinguishing"
    FLOOR = "Floor"
    FLOORING_SURFACE = "Flooring (surface)"
    FURNISHING = "Furnishing"
    GOOD = "Good"
    HVAC_EQUIPMENT = "HVAC equipment"
    KEY = "Key"
    LIGHTING = "Lighting"
    MOB_TOOL_INSTRUMENT = "Mob.tool / Instrument"
    MOBILE_DEVICE = "Mobile device"
    OTHER_IT_EQUIPMENT = "Other IT Equipment"
    PART = "Part"
    PERISHABLE_ELEMENT = "Perishable element"
    PRINTER = "Printer"
    PROPERTY = "Property"
    REAL = "Real"
    RESOURCE = "Resource"
    ROOM = "Room"
    ROOM_APPLIANCES = "Room appliances"
    SAFETY_EQUIPMENT = "Safety Equipment"
    SHERQ_EQUIPMENT = "SHERQ equipment"
    SIGN = "Sign"
    SITE = "Site"
    SOFTWARE_LICENSE = "Software License"
    STAIRWELL = "Stairwell"
    SUITE = "Suite"
    SURVEILLANCE = "Surveillance"
    TELE_WORKING_WORKPLACE = "Tele-working Workplace"
    UNIFORM = "Uniform"
    VEHICLE = "Vehicle"
    VERTICAL_TRANSPORT = "Vertical Transport"